values = [
    "Guillem TD (Mixu)",
    "Sirena Trempats Castells",
    "andrea grau (triumfa)",
    "Carla Jutglar",
    "Marina Canalla Trempats",
    "Gurru Laia Gurrutxaga Castells Trempats",
    "Joan Juanito Trempats",
    "Kai",
    "Mel Palos Mato Trempats",
    "janaa tripi",
    "Uriel Minga Trempats",
    "Marta Bernaldez Tuki Trempats Castells",
    "ari Floreta Trempats Castells",
    "Reina Casa Papa",
    "Telegram",
    "Ares Aleix",
    "Comi Popop",
    "SCF - Barcelona",
    "GetIDs Bot",
    "SabaGram",
    "BAAAASSS",
    "Ferran Elena Elias",
    "Nova comi gespa",
    "T-mobilitat Atenció",
    "Raska Ainhoa BcTours Puerto",
    "Arantxa Madriz Granada",
    "Batfolrades🦇",
    "Néstor Punqui Mer",
    "Mama Sushi Trempars",
    "Jordà Sanchez",
    "Andrea Bertolero (dorayaki)",
    "Marina (Nanu)",
    "Edu Tuno",
    "Yuni",
    "Olga (vellaca)",
    "Alba",
    "marti/obridor",
    "Sergio (Ventafocs) :)",
    "Aineet",
    "Sara Barbé",
    "Sara🦎 (rusalia)",
    "Diplo",
    "Daniel G. Crespo",
    ". .",
    "Laia Coronado Nadal",
    "Eric",
    "Marc Fusté",
    "Sònia",
    "Maria Bru",
    "Adri",
    "Gerard Bruguera",
    "Juju (Judith)",
    "Carles Paré (Peri)",
    "R@sto",
    "Elisenda Rovira",
    "Altuna",
    "Àlex Llambrich",
    "Eloy",
    "Marina Amorós",
    "Manu",
    "reshu",
    "Aarroncar",
    "Núria Corominas",
    "Ena",
    "Antonio Trempats",
    "Tusa",
    "Pat Mer UPF",
    "maria (medi)",
    "DEKA",
    "Marc Ska",
    "Gabriel🦊",
    "David Floquemu🗿",
    "Uri Trempats Roco",
    "berta jazz",
    "Claudia (flusky)",
    "Mireia Mati💃 Trempats",
    "iria Trempats Castells",
    "Aleix Astro Trempats",
    "susi🫶🏼 (Sushi) Trempats",
    "Mane Trempats",
    "Pere De Solà-Morales Casals",
    "Sonia Pedrola",
    "Lillie",
    "Moncho",
    "Silvia Colom Cometa Trempats",
    "Mimoso✨",
    "vall bass",
    "cristu (martí)",
    "Caballero🐻",
    "Irene (Badgyal)",
    "Paula Costa",
    "Arnau Roca Trempats",
    "Laisa Bonin",
    "Anna Salido",
    "Jordi (Kali)",
    "Xavi/Guaḥe",
    "Silvia Silbato Trempats",
    "Eric 8mil Trempats",
    "Cèlia",
    "Isaac Trempats",
    "karla (qk)",
    "Miquel Bisbe (lleó🦁)",
    "Josep Xolo Trempa",
    "Pinxo (Ferran)",
    "Tarik",
    "Angela Planas Gueto Trempats Castells",
    "nil :) Esmolet Trempats",
    "Ortua (Irene)",
    "Sergi Puig",
    "Alba (Arròs🍚)",
    "Ari Coro Trempats Castells",
    "joan ayza Casalla Trempats Castells",
    "Pere (Keta)",
    "Quim (mimo)",
    "papallona amàlia🦋",
    "Albert Gos Trempats",
    "Ariel (espuma)",
    "Carla Piñera",
    "Samuu Trempats Castells",
    "Martina petita",
    "Farners",
    "Carmona",
    "carlota Marqueta",
    "David Gacía Subirats",
    "Laura Pisa Aragon",
    "Filiberto (Lluc)",
    "Tini",
    "Sebastian :):)",
    "Aixa (Mao)",
    "Adrià Febrer Trempats",
    "Ena",
    "raquel (ambar)",
    "miranda (berru)",
    "Marta Rey Rostoll",
    "Pau G",
    "Pol Calsina",
    "Erik (Tinto 🍷)",
    "Joana Gimbernat",
    "Laura Polo Dalfó",
    "GANSO Masó",
    "Joana",
    "Joan Garcia",
    "èlia / crisma",
    "Aina / caos",
    "Alex Teixido",
    "Ibu (Aina)",
    "Lia",
    "Floren Ventura",
    "Clàudia",
    "mar casellas (damm)",
    "judith (tinky)",
    "eloi",
    "Èlia",
    "Laia Lloreda",
    "Oleguer (Hop)🐇",
    "LianT",
    "Martina",
    "Oriol Salat",
    "Peiret Castells Trempats",
    "Joan Angerri",
    "joana aymerich",
    "Jansi (Moana)",
    "Farraona",
    "Ari2",
    "Dior",
    "Irune Vela Casabón",
    "Candela Serena Candy Trempats Castells",
    "berta orriols (wachi)",
    "Pau (Kiwi)",
    "Marc S (Gaspi)",
    "Marina G (nones)",
    "Pere Burgués Carreño",
    "Lluís Fonsi",
    "Markel (xake)",
    "anna (galileo)",
    "Aitana (daura)",
    "foix (guineu)",
    "Judith Mandra Trempats Castells",
    "Sergi Mosquera",
    "oriøl",
    "Noel",
    "Tuset (Sutton)",
    "guiomar (gigi)",
    "Eudald (Dublín)",
    "Legends",
    "Hazelnut's League ⚽️🍻🍾",
    "BARRA dinar 10è",
    "Cibersec Ágora",
    "SabaGram",
    "ansiyu Trempats",
    "Nemo Trempats",
    "Gemma (bolet)",
    "Excursió ensaïmada 🥐",
    "Bombolonies '24",
    "Carles Pons",
    "Laia Dosta",
    "Enric Pissarra Fumon Trempats",
    "Berni",
    "Txamo",
    "animació furbo💃🤩🤪",
    "Aleix Capó",
    "Sofia (Petri) Trempats Castells",
    "Berta Sellarès (mouse)",
    "anna (galileo)",
    "Belma",
    "Cris Sidra",
    "Martina petita",
    "Farners",
    "Carmona",
    "carlota Marqueta",
    "David Gacía Subirats",
    "Laura Pisa Aragon",
    "Filiberto (Lluc)",
    "Tini",
    "Sebastian :):)",
    "Aixa (Mao)",
    "Adrià Febrer Trempats",
    "Ena",
    "raquel (ambar)",
    "miranda (berru)",
    "Marta Rey Rostoll",
    "Pau G",
    "Pol Calsina",
    "Joana Gimbernat",
    "GANSO Masó",
    "Joana",
    "Joan Garcia",
    "èlia / crisma",
    "Aina / caos",
    "Alex Teixido",
    "Ibu (Aina)",
    "Lia",
    "Floren Ventura",
    "Clàudia",
    "mar casellas (damm)",
    "judith (tinky)",
    "eloi",
    "Èlia",
    "Laia Lloreda",
    "LianT",
    "Martina",
    "Oriol Salat",
    "Joan Angerri",
    "joana aymerich",
    "Laura Polo Dalfó",
    "Erik (Tinto 🍷)",
    "Paula Bozzo Trempats",
    "Avril Giné Sito Trempats",
    "aina - fum💨💨",
    "gabrielaa",
    "Gerçao Maravillao",
    "Júlia Juvi Vila Trempats",
    "Sara",
    "Elena B",
    "Lucia Peñalver Planas",
    "lluna 🏴‍☠️ (pirata)",
    "alice",
    "Oleguer (Hop)🐇"
]



done = {'Irune Vela Casabón': False, 'Mane Trempats': True, 'Mel Palos Mato Trempats': True, 'Marta Rey Rostoll': False, 'Marc *Calvo*': False, 'èlia / crisma': False, 'eloi': False, 'Kai': True, 'Alex Alsemito Trempats UPF': True, 'Joan Juanito Trempats': True, 'Joan Angerri': False, 'Gurru Laia Gurrutxaga Castells Trempats': True, 'Albert Gos Trempats': True, 'Pere (Keta)': True, 'Marina Canalla Trempats': True, 'ari Floreta Trempats Castells': True, 'Berni': True, 'David Gacía Subirats': False, 'Ari2': False, 'Marta Bernaldez Tuki Trempats Castells': True, 'Joana': False, 'Uriel Minga Trempats': True, 'mar casellas (damm)': False, 'janaa tripi': True, 'Markel (xake)': False, 'Aixa (Mao)': False, 'Candela Serena Candy Trempats Castells': False, 'Carles Pons': True, 'Carla Jutglar': True, 'Tuset (Sutton)': False, 'andrea grau (triumfa)': True, 'Sirena Trempats Castells': True, 'LianT': False, 'Clàudia': False, 'Pol Calsina': False, 'Eudald (Dublín)': False, 'Guillem TD (Mixu)': True, 'nora massegú (gufi)': True, 'Samuu Trempats Castells': True, 'Noel': False, 'Avril Giné Sito Trempats': False, 'Carla Piñera': True, 'guiomar (gigi)': False, 'Belma': False, 'Ariel (espuma)': True, 'Arnau Roca Trempats': True, 'Sofia (Petri) Trempats Castells': True, 'Mara': True, 'joan ayza Casalla Trempats Castells': True, 'Alfons (Xop)': True, 'papallona amàlia': True, 'Sergi Mosquera': False, 'rita Rifu Fuertes Trempats Castells': True, 'Dior': False, 'anna (galileo)': False, 'Laura Pisa Aragon': False, 'Sito': True, 'Oriol Salat': False, 'foix (guineu)': False, 'Albert Blasco': False, 'Nerea Tarifa': False, 'Bernat Girabal': False, 'aina - fum': False, 'Mireia Serrat Trempats Castells': True, 'Quim (mimo)': True, 'Mariona Maria': True, 'Erik (Tinto )': False, 'Martina': False, 'Martina (Tram)': False, 'Arnau Munsó Giró': True, 'Maverick': True, 'Tarik': True, 'Àlvar Trempats Castells': True, 'Sandra': False, 'Paula Carulla': False, 'Ari Coro Trempats Castells': True, 'Juls (Trotsky)': True, 'Nil': False, 'Alba (Arròs)': True, 'Sergi Puig': True, 'noah': False, 'Marc S (Gaspi)': False, 'Ortua (Irene)': True, 'berta orriols (wachi)': False, 'Txamo': True, 'Ibu (Aina)': False, 'Beth': False, 'Nil Trempats': True, 'Aleix Capó': True, 'nil :) Esmolet Trempats': True, 'Berta Sellarès (mouse)': True, 'Adrià Febrer Trempats': True, 'Angela Planas Gueto Trempats Castells': True, 'Cris Sidra': False, 'miranda (berru)': False, 'Filiberto (Lluc)': False, 'Alba Valero': False, 'karla (qk)': True, 'Aitana (daura)': False, 'Bernat Rustu': False, 'lluna (pirata)': False, 'judith (tinky)': False, 'Farners': False, 'carlota Marqueta': False, 'Pinxo (Ferran)': True, 'Xavi Riera': False, 'Joan Garcia': False, 'Xavi/Guaḥe': True, 'Josep Xolo Trempa': True, 'Sebastian :):)': False, 'Júlia camps': False, 'Wagner': True, 'alice': False, 'boira (maria)': False, 'joana aymerich': False, 'Miquel Bisbe (lleó)': True, 'Jordi (Fuet-castells)': True, 'Laia Lloreda': False, 'Carmona': False, 'Jona': False, 'Enric Piñera i Pons': False, 'Isaac Trempats': True, 'Rut Cabús Tur Trempats': True, 'Xorro': False, 'Cèlia': True, 'Trk (Branca)': False, 'Eric 8mil Trempats': True, 'Cèsar (alea)': False, 'Joana Gimbernat': False, 'Carol Rius': False, 'Silvia Silbato Trempats': True, 'Aina / caos': False, 'aina pons': False, 'Sara': False, 'Paula Bozzo Trempats': False, 'Elena B': False, "Lidia(lind'or)": False, 'Rodrigo Gonzalez (RATO)': False, 'Nemo Trempats': True, 'Irene (Airin)': False, 'bruno': False, 'Farraona': False, 'Jansi (Moana)': False, 'Biela': False, 'Jordi (Kali)': True, 'Guillem': False, 'Oleguer (Hop)': False, 'Pau (Kiwi)': False, 'Albert': True, 'raquel (ambar)': False, 'Judith Mandra Trempats Castells': False, 'laia ubeda': True, 'Cristina Llobet (Llop)': False, 'Pau G': False, 'GANSO Masó': False, 'Uri': False, 'Judit Ángel': False, 'Júlia Juvi Vila Trempats': False, 'Charlie (Wonka)': True, 'Ignasi Salat': False, 'Pol Guasch': False, 'Enric To': False, 'Maria París': False, 'Lluís Afonso': False, 'Anna Salido': True, 'Laisa Bonin': True, 'pau': False, 'Gerçao Carles Paré (Peri)': False, 'Pat Mer UPF': True, 'Tusa': True, 'R@sto': True, 'Antonio Trempats': True, 'Elisenda Rovira': True, 'Altuna': True, 'Àlex Llambrich': True, 'Eloy': True, 'Marina Amorós': True, 'Manu': True, 'reshu': True, 'Aarroncar': True, 'Núria Corominas': True, 'Gemma (bolet)': True, 'Èlia': False, 'Lucia Peñalver Planas': False, 'Gerçao Maravillao': False, 'gabrielaa': False, 'Lluís Fonsi': False, 'Tini': False, 'Marina G (nones)': False, 'Enric Pissarra Fumon Trempats': True, 'Martina petita': False, 'júlia alegre (haxis)': False, 'Anna Campàs': False, 'Alba (RIGA)': False, 'oriøl': False, 'Laura Polo Dalfó': False, 'Laia Peiró Trempats Castells': True, 'Paula Costa': True, 'Mimoso': True, 'marcos': False, 'Irene (Badgyal)': True, 'Angel de Felipe Sainz': False, 'Jonka': False, 'mario': False, 'Vincent': False, 'SOTO Paula Soto Reina': False, 'Afra Tarradas Olivé': False, 'Maria Mas': False, 'Gemma Ayats': False, 'Sergi': False, 'jana (queen)': False, 'GUMET': False, 'meritxell': False, 'Lady': False, 'Lia': False, 'Apolo': False, 'Helena / Goliat': False, 'Caballero': True, 'cristu (martí)': True, 'Aleee (Gat)': False, 'Jules Jofra': False, 'Moya': False, 'Uri Pallaflam': False, 'mariona carbó ️': False, 'Núria (Aspa)': False, '@@@ - lisa': False, 'Carla (Varas)': False, 'vall bass': True, 'Miquel (uep!)': False, 'Aner (Puyol)': False, 'Pere Burgués Carreño': False, 'Jordi Farre Flotats': False, 'Silvia Colom Cometa Trempats': True, 'Alex Teixido': False, 'Farlopa': False, 'rovelló (lluc)': False, 'ᴘᴀᴜ ☭': False, 'Jujuu': False, 'María Urbasos Miravé': False, 'Moncho': True, 'Oscar Duran': False, 'Uxía': False, 'Floquet (gisela)': False, 'Neus Roca': False, 'Ariadna Bajona': False, 'Laia Bessó (Bessoneta)': False, 'Enric': False, 'Ari Riera': False, 'Pau': False, 'Gerard (Geri)': False, 'Judit': False, 'Aniol Xolís': False, 'Albert Solanes': False, 'Gabarró': False, 'JB': False, 'mariona(galàn)': False, 'Anna Fadi': False, 'Júlia (einstein)': False, 'Inés': False, 'Victor (Vitti)': False, 'aina': False, 'Miquel Alcarria': False, 'Keli (Ari)': False, 'Núria Lopera': False, 'franco vitola': False, 'Sam Gardner': False, 'Biel Roquet': False, 'Núria Coll': False, 'Villarejo Tu Papá': False, 'Fidel': False, 'Maria Farràs': False, 'Lillie': True, 'belén (newton)': False, 'xuculita': False, 'Adrià Canyelles (canyes)': False, 'montana': False, 'Aina Eberlé': False, 'Laia Sevillano': False, 'Martí Fabrés': False, 'Marc Rivera': False, 'Txell Muntané': False, 'Marc Anglès': False, 'Sonia Pedrola': True, 'Joan Esquirol': False, 'Laia Fontbona': False, 'Biel (Eliot)': False, 'Alexandra Codina': False, 'Laia Homdedeu': False, 'Ton Linus': False, 'Pere De Solà-Morales Casals': True, 'Marta (Pagu)': False, 'Alba Abelanet (Maia)': False, 'Gerard Bono': False, 'Aina Roglan': False, 'Josephine Cretin': False, 'Ariadna Márquez': False, 'Alex Baquer': False, 'Amèlia :)': False, 'Pich': False, 'violeta (alaska)': False, 'Mayayo': False, 'Lucia Matamoros': True, 'sira': True, 'Ana Fariña': True, 'asha': True, 'Yubei Castellà': True, 'Gemma Simon': True, 'Elens B': True, 'Judit Olives Llabres': True, 'Miki Redo': True, 'Alex Codina (Riuda)': True, 'Sandra (Aquiles)': True, 'Març': True, 'herbes': True, 'Nidà Farooq': True, 'Andrea Bertolero (dorayaki)': True, 'Peiret Castells Trempats': True, 'susi (Sushi) Trempats': True, 'Jan Trempats': True, 'Uri Trempats Roco': True, 'Aleix Astro Trempats': True, 'iria Trempats Castells': True, 'ansiyu Trempats': True, 'Mireia Mati Trempats': True, 'David Floquemu': True, 'Claudia (flusky)': True, 'berta jazz': True, 'DEKA': True, 'Olga (vellaca)': True, 'Marina (Nanu)': True, 'Ena': True, 'marti/obridor': True, 'Edu Tuno': True, 'Yuni': True, 'Mireia CRESPI': True, 'Gabriel': True, 'Laia Dosta': True, 'Alba': True, 'Sergio (Ventafocs) :)': True, 'Lidia (GTA)': True, 'carcellé': True, 'Marc Ska': True, 'Vinyet': True, 'Cisco': True, 'adriana (pastis)': False, 'Nit-Ari': False, 'A': False, 'Alba (Maduixota)': False, 'Uri2': False, 'maria (medi)': True, 'Aineet': True, 'Floren Ventura': True, 'Sara Barbé': True, 'Sara (rusalia)': True, 'Diplo': True, 'Daniel G. Crespo': True, '. .': True, 'Laia Coronado Nadal': True, 'Eric': True, 'Marc Fusté': True, 'Sònia': True, 'Maria Bru': True, 'Adri': True, 'Gerard Bruguera': True, 'Juju (Judith)': True, 'Carles Paré (Peri)': True}


for vale in values:
    done[vale] = True
print(done)

count_true=0
for d in done:
    if done[d]: count_true+=1
print(count_true)